server:
  port: 9090

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: test
          uri: http://www.naver.com
          predicates:
            - Path=/test/**
          filters:
            - name: MemberFilter
              args:
                baseMessage: test filter 입니다.

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

