server:
  port: 9090

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: test
          uri: http://www.naver.com
          predicates:
            - Path=/test/**
          filters:
            - name: MemberFilter
              args:
                baseMessage: test filter 입니다.

  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/newstar?serverTimezone=Asia/Seoul
    username: root
    password: root

  data:
    redis:
      host: localhost
      port: 6379


logging:
  level:
    org.springframework.cloud.gateway: DEBUG

